<?php $_result='<?xml version="1.0" encoding="windows-1252" ?>
<!-- RSS generated by PHPBoost on ' . $_data->get('DATE_RFC822') . ' -->

<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
	<channel>
		<title>' . $_data->get('TITLE') . '</title>
		<atom:link href="' . $_data->get('U_LINK') . '" rel="self" type="application/rss+xml"/>
		<link>' . $_data->get('HOST') . '</link>
		<description>' . $_data->get('DESC') . '</description>
		<copyright>(C) 2005-' . $_data->get('THIS_YEAR') . ' PHPBoost</copyright>
		<language>' . $_data->get('LANG') . '</language>
		<generator>PHPBoost</generator>
		
		';foreach($_data->get_block('item') as $_tmp_item){$_result.='
		<item>
			<title>' . $_data->get_from_list('TITLE', $_tmp_item) . '</title>
			<link>' . $_data->get_from_list('U_LINK', $_tmp_item) . '</link>
			<guid>' . $_data->get_from_list('U_GUID', $_tmp_item) . '</guid>
			<description>' . $_data->get_from_list('DESC', $_tmp_item) . '</description>
			<pubDate>' . $_data->get_from_list('DATE_RFC822', $_tmp_item) . '</pubDate>
			';if ($_data->is_true($_data->get_from_list('C_ENCLOSURE', $_tmp_item))){$_result.='
			<enclosure url="' . $_data->get_from_list('ENCLOSURE_URL', $_tmp_item) . '" length="' . $_data->get_from_list('ENCLOSURE_LENGHT', $_tmp_item) . '" type="' . $_data->get_from_list('ENCLOSURE_TYPE', $_tmp_item) . '" />
			';}$_result.='
		</item>
		';}$_result.='
	</channel>
</rss>'; ?>